### ISSUE TITLE
revB checklist

### ISSUE THREAD

**Issue by barawn** [barawn/helix-mtrig#1]
- [x] SPI programming
- [x] DC-coupled busy lines (BOM issue only, just use 0 ohm 0402s)
- [x] Pulls on power controls
- [x] 3.3V on GPIO connector
- [x] Replace PCIe clock fanout and FPGA SYSCLK fanout chips due to availability
- [x] Redo trigger input connector

**Comment by barawn** [comment]
thinking that I'm going to replace the trigger input connector with a ribbon cable to a daughterboard, as we need a jumper there anyway to get to a front panel. Makes it a *ton* easier to assemble internally.

This will be an FFTP-13 connector, which will fit inside the footprint of the mini-SAS if we don't use locking connectors, and I'll probably just strain-relief them against the mounting board using the mount points. I can also probably use locking connectors if I stagger them vertically, which probably makes sense.

**Comment by barawn** [comment]
- [x] redo B3U-1100 to allow for boss option (add hole)
- [x] finish GND routing on new trigger connectors
- [x] length match clock outputs
